version: '3.8'

services:
  # Scira2API应用服务
  scira2api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: scira2api:latest
    container_name: scira2api
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      # 必需配置
      - USERIDS=${USERIDS}
      
      # 可选配置
      - PORT=${PORT:-8080}
      - APIKEY=${APIKEY:-}
      - MODELS=${MODELS:-gpt-4.1-mini,claude-3-7-sonnet,grok-3-mini,qwen-qwq}
      - RETRY=${RETRY:-1}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - BASE_URL=${BASE_URL:-https://scira.ai/}
      - CLIENT_TIMEOUT=${CLIENT_TIMEOUT:-300}
      - CHAT_DELETE=${CHAT_DELETE:-false}
      - READ_TIMEOUT=${READ_TIMEOUT:-30}
      - WRITE_TIMEOUT=${WRITE_TIMEOUT:-30}
    
    volumes:
      # 日志持久化
      - ./log:/app/log
      # 配置文件挂载（可选）
      - ./.env:/app/.env:ro
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # 网络配置
    networks:
      - scira2api-network
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

# 网络定义
networks:
  scira2api-network:
    driver: bridge
    name: scira2api-network

# 卷定义
volumes:
  scira2api-logs:
    driver: local
    name: scira2api-logs